### ISSUE TITLE
NFCリーダー

### ISSUE THREAD

**Issue by lotz84** [camphor-tokyo/attendance#1]
- [x] NFCリーダー & Raspberry Pi の購入
- [x] SuicaからIDの取得
 - [] ~Suica & Raspberry Pi で出席APIを叩く~
- [x] 直接 Slack の incomming webhook を叩く

**Comment by lotz84** [comment]
発注済みとのことなので次回定例で触りたいですねー！

**Comment by shotarok** [comment]
**参考になりそうなリンク**
- NFC library
  - [libnfc (C)](http://nfc-tools.org/index.php?title=Libnfc)
  - [nfcpy (python)](https://github.com/nfcpy/nfcpy)
  - [nfc (rust)](https://github.com/dsgriffin/nfc)
- サンプル集
  - [Raspberry Pi Drives ITEAD PN532 NFC Module with libnfc](https://www.raspberrypi.org/forums/viewtopic.php?f=45&t=78966)
  - [nfcpyでお手軽NFC開発[1/2]](http://techblog.qoncept.jp/?p=165)
  - [nfcpyでお手軽NFC開発[2/2]](http://techblog.qoncept.jp/?p=175)
  - [玄関をSuicaで開ける](http://coro.hatenadiary.jp/entry/2015/12/23/233434)
  - [Raspberry PiでFelicaのIDmを表示する](http://qiita.com/ihgs/items/34eefd8d01c570e92984)

**Comment by shotarok** [comment]
OSX で nfcpy の動作確認手順.

``` bash
# nfcpy を動かすための library
$ brew install libusb libusb-compat bzr
# nfcpy は python3 では syntax error が出たので, python2 で環境を用意
$ virtualenv -p /usr/local/opt/python/bin/python2.7 venv
$ source venv/bin/activate
# 依存ライブラリをインストール
$ pip install pyusb libusb1 pyserial
# nfcpy のダウンロードとサンプルの実行
$ bzr branch lp:nfcpy
$ python nfcpy/examples/tagtool.py
> python nfcpy/examples/tagtool.py
> [nfc.clf] searching for reader on path usb
> [nfc.clf] using SONY RC-S380/P NFC Port-100 v1.11 at usb:020:002
> ** waiting for a tag **
> Type3Tag 'FeliCa Standard (RC-S???)' ID=0000000000000000 PMM=0000000000000000 SYS=0000
```

 参考: [Mac + RC-S380でSuicaを読み込む](http://t-kashima.hateblo.jp/entry/2016/03/03/031133)

**Comment by shotarok** [comment]
SuicaからIDの取得 →  done

test.py : https://gist.github.com/shotarok/fed595781b55330e3137b5b5b072cf91

[![https://gyazo.com/8912c1d5243b629e6eaf9aa273055b67](https://i.gyazo.com/8912c1d5243b629e6eaf9aa273055b67.gif)](https://gyazo.com/8912c1d5243b629e6eaf9aa273055b67)

**Comment by morishin** [comment]
ラズパイで register.py 動かしたら No such device って言われた
lsusb したらデバイスは認識されてたから、 Python 側から見つけられてないみたい

**Comment by shotarok** [comment]
> ラズパイで register.py 動かしたら No such device って言われた
> lsusb したらデバイスは認識されてたから、 Python 側から見つけられてないみたい

返事が大変遅れて申し訳ないです :bow: sudo を付けないと python から認識できないみたい.
以下のコマンドがラズパイ上で動くことを確認しました

``` bash
$ sudo venv/bin/python2.7 register.py
$ sudo venv/bin/python2.7 attendance.py
```

**Comment by shotarok** [comment]
#9 #10 でAPIではなく、直接 Slack の Incomming webhook を叩く形式に変更し機能をリリースしたためクローズ.
