### ISSUE TITLE
APIサーバー

### ISSUE THREAD

**Issue by lotz84** [camphor-tokyo/attendance#3]
- [ ] API 仕様決める
- [ ] 出席API実装
- [ ] 出席者一覧取得API実装
- [ ] 退出API実装
- [ ] 新規登録API実装

**Comment by morishin** [comment]
いい感じにお願いします @ryota-ka

**Comment by ryota-ka** [comment]
@morishin https://github.com/khibino/haskell-relational-record

**Comment by shotarok** [comment]
API を使用せずにラズパイローカルの DB を使う設計に変更したためクローズします
